language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - your@Email.com

addons:
  sonarcloud:
    organization: "pinepond"
    token:
      secure: "qJtb/wVJYIUGFQmqLyVg/mWflo7tc7C50wVVRN3806pSKTJtYxtZVwhdBclxx9ZsXpDDMGm1zkNX0M0iB2FXmfcc+OHKQhE5PNiToBppChzuVT8MM3NbOYIu0Q8Zk3Pi0ZtIYe8eYJkSBmnMVcTkA7EOsp9nLQUjT2Td6vtC/6YssZII0tYwO2Z/OiIrWB6tmKLTqtjvXzrd4f7ulMqOdyykN48ERKeyCErvh7aDL3rnapfiKlxStMOJddMEBalcybyGe4v+h/ElsN04A6m8ccRBQ0XigeOQ2VXJ3nyLRFpdt7ySuCzxPWc8dfbLqrY/zb1JBBaU98tpoFaftu1LjR9FNoa7GZRlv30IifluIiYilNWtbx4YEMoTIAE+hOzAb5j8r8eHjsfWleGZNf2BXyQwzAhazi8BvcKbJWh0dOb7nVKZeSSQ8+mQu+oYuZmAMP0uMQJbEtSk/3EsJxQQ+m9nUgwRW/RhjM9GexkKtbNzacnUTGaOOSCIArlkTT3DtnP+65C1Xo6lbQUGtB7u+u+8Vmxq7qzZ+QN7+sMubKHSPsOAWBBcwfUQpiN7Px3T8QQd9a9T3FUMcW2DfnKKM4nDr4AQtSdRxswrQlFIWmXFv5d6Ozg3HWAke2e4PyU7cj5Y5GT81QbjBtf9EZPtGzwmuSh6Ycsah05sCPQMgqE="

#-Dsonar.login=0b9e5f5db5ae5ed4207950595e45a1fec955dd9a
script:
  - mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
  - find ./ -name "%jacoco%"
  - mvn -B sonar:sonar -Dsonar.projectKey=Pinepond_egovframe-runtime  -Dsonar.coverage.jacoco.xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ',')