language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - your@Email.com

addons:
  sonarcloud:
    organization: "pinepond"
    token:
      secure: "JJzE/nK5VnI2P95XIwK9x128ZG5kCFIL6YVb2a+FylRJsPbOB//qJQXvodji5LaUpE6fFRtYjuiP1P/fVG2wTsy7o5q7j2qjdMXxhYy1djjzavfhyHznE9c6/y5/cYf4X9mDH25Pnal2ho5CwwDnBM/lXQWDPoVrAd7cMfX6Qtr80Y71Bz360CZ6Zq6i9kb0ZXeeWAhEu0JhvmNR+MJBjQ6ZNhWRtuQwJi8uJ4Jrvm3d1IVy2ZiEuWV+F+jMS+AFxmEDI/EZ97kM5cKRbxicGYibHbB3tlrUmLjVqm1eFA9lF/hzhZ4QBGvREAU0p2x1r2LIKjZXd3uCun4P2bzTlLy5U7vcx+tdBMZX/fcumfKxRIIkF+wBzAt3FzyODJjx26uOx8BgOuHONm9SwtBq73oP0+YJNdSEHPZzsPqEA/AIGQpyK28esGqZX55dae8u1R8T/vWAMEQLOb0C9pNPECmUBwUSGDjHAP4QKIKlrpLQaz1IN3LlfnOj8RRA0ErRIk8kUuc4Kk2qUhEsdDLr3dg7ua7GZUfShZclAsPVcqYlUO/OftI+m1VM3q87MZlGE8CgpAEHmY5qCvZwmBvzDzzwjeX+0PNMLcOXfQCbDfsHW/GJeNkCCU0YCA4xXUhrPz1z/Y1A93dxpcJmniXgZqWch4cj8drBIE4oU3Vm5bc=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar