language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - your@Email.com

addons:
  sonarcloud:
    organization: "pinepond"
    token:
      secure: "SA76Z46k8Jr2aQlVNZYo0T8JK1+F8Rf0yfRM+ezqJ3LG9NWvFZi/4d6NgSk1WBImJBUZ+Hof4T9YJr9/coz+enxbUPePAdfX9/p2BRp4F7kfz/8PNNWsW4pS8NTj7s5lhhqLBNWGNRQH1zOhtRB4JEsX3nkyW0T3IN8wB/WHmWU6n4IRTRBfDGUlsusKNjETTuBkR/1PUpjlAxdPF2AZLjC8QwwT0PAwH7uMQOaKuEOzXD2MdD9LRCmZijNiiZ8Lp9iijCMbK/ntDJk0I8uXa7XhIX26afxXeiDTE7pgDmt5SqCEeuIKbXD22q6Iqgog8vTWy0VJeReAiFBrqfvclwdZgsqFNCHS4yhkWn8hNFhliVI3E8ikchoWu9oMW62ivup5oKQnJpfXCkVaEZ5L5s0tRqEwiSgO0TIngTIEONecCyA0TWgL80eDU4FwJodK8whrEJzbX03osLX/q+4Z8NcYzwYEcu8Kf6n64auE5IoGXui97IiDSGRnp0qB5X+ILpK/m9TTfpCQnXoZKoPCdGA6ERW0+g5DYELDtPrCOsgsMwPWgZ0ZxUfMNHdpYid/nXwkEo0JoSgEZFJSdQ0sEJWsjTNubiFYg4QOqKqykpW6saQj5fzn2EHmCUxamuKyUZhNNFh44wikdMkB2j6by8IldeP1qZ5usaR5OnRLwNw="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
  - mvn sonar:sonar  -Dsonar.projectKey=Pinepond_egovframe-runtime -Dsonar.login=0b9e5f5db5ae5ed4207950595e45a1fec955dd9a