language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - your@Email.com

addons:
  sonarcloud:
    organization: "pinepond"
    token:
      secure: "D9ZecYgZD+g7kIQPeYYmBhAicvbKLV3IKNdKTyfusIiLCF0EkXUKRyQfnwaiQru9NEyJEAjv/qFTyTl/ml6GhWgTvYtvyl2KIwbcmaKMTGNwyatJkYjIvrb8+8YpCcJRtuyPLriXuM0uPoTH9XlBTZ3h124vTwHiRhPU9eK/vyGMtfzt5VZGUmDoO0DzYHZQdBXvxrQ54TWcOP6YZGW13W7L7SeUXnmD+V7R3+3UQ5UZIFKYCzZpzPJe2GS6OqVjPiXYXZ/JhKUJcHXFPYEy364DNFBH12J23lziMqtD8AXJ7No4R/mpfugDRDhLbs7Dt7aA/zcCu/xjNaOChE/iAEMvwjbvC0Ie7QzyWeGxm7Ho6lan1l73DDFloeMl5MazAWVeQleuDyqQnNztVmpEwxlGevRC5g01jT9hOy1HjmQ6GSojI2pZmcN1rhVOE1jswlZ07O2pOG8K1dQulSbDljAbxpaYcZz99QSsCEBpefNogqgL+rdHQ/7Pp/gVqGw3/z4zB3kFmpk5Pq9HjcOj3yi1jzF9V99VZA15+X3N68iwdZ8ubP9BuJvQoxR5msR2st3B0NnfAfZNCJUHpjtYGbzGynWxGRXh35dzy9PPOg54Yoh1TOFAkEa1UYp93HEeggu+4VpLNv7eEfJhIfMBRoKJkAJaMDSRyNfBNTgJp1M=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=0b9e5f5db5ae5ed4207950595e45a1fec955dd9a